### ISSUE TITLE
Add option to enable only in blocks where brackets are present

### ISSUE THREAD

**Issue by willishq** [getify/eslint-plugin-proper-arrows#1]
**[EDITORS NOTE: This issue was transferred from another repository, so it may no longer be valid, still TBD]**

I personally can see merit to using anonymous functions using the shorthand syntax when doing simple calculations for filters and mapping arrays, for instance.

I would like the ability to only apply the rule when the arrow function contains curly brackets, so this should be fine

```js
[1, 2, 3].map(x => x * 2).filter(x => x < 4);
```

But this wouldn’t be, without a reference to `this`

```js

new Array(6).fill(undefined).map((_, key) => {
   let thing = DoSomething(key);
   return thing();
}
```

I’m in two minds as to what to do about returning objects:

```js

x => ({
  …
})
```

I’ve never used this syntax because it’s too messy in my opinion, but I think it should be part of the rule options too, which may complicate things because of the brackets.

**Comment by getify** [comment]
I've transferred this issue over to this new project. It may not be valid anymore, I'm not sure. Please check out this package's "object-return" rule to see if it is helpful.

**Comment by getify** [comment]
I think I will close this issue for now, but please feel free to re-open it if you think it needs to be re-considered.
