### ISSUE TITLE
Prevent arrow functions that implicitly return arrow functions

### ISSUE THREAD

**Issue by Dan503** [getify/eslint-plugin-proper-arrows#14]
I'm not sure if this rule exists already or not.

I find it hard to read arrow functions that return arrow functions like this:

```js
var x = (a,b) => () => a + b;
```

I think having a more explicit return is easier to read.

```js
var x = (a,b) => {
  return () => a + b
};
```

**Comment by getify** [comment]
Yes that rule exists: "return" rule, "chained" mode. :)
