### ISSUE TITLE
Errors when disabling the rules in Create React App

### ISSUE THREAD

**Issue by davidwkeith** [getify/eslint-plugin-proper-arrows#25]
I am getting the following error when I add the rules to a CRA app and try and disable existing errors:

```
Line 1:1:  Definition for rule '@getify/proper-arrows/return' was not found  @getify/proper-arrows/return

Search for the keywords to learn more about each error.
```

The eslint-disable directive is as follows:

```javascript
/* eslint-disable @getify/proper-arrows/return */
```

**Comment by getify** [comment]
For ESLint comments, I think you need `"` quotes around the `@getify/proper-arrows/return` part.

**Comment by davidwkeith** [comment]
Weird, ESLint doesn't require quotes, but when run through CRA it does. Will try. Thanks!

**Comment by getify** [comment]
I think ESLint does require quotes for scoped plugins.

**Comment by getify** [comment]
Closing for now.
