### ISSUE TITLE
`where` rule global option detects passing arrow as callback on module level as violation

### ISSUE THREAD

**Issue by Guria** [getify/eslint-plugin-proper-arrows#32]
Given code
```
const App = React.lazy(() => import('./SomeComponent'));
```
with config 
```
    "@getify/proper-arrows/where": [
      "error",
      { global: true, property: false, export: true, trivial: false },
    ],
```
causes violation reported:
`Arrow function not allowed in global/top-level-module scopeeslint(@getify/proper-arrows/where)`

**Comment by Guria** [comment]
```
const routes = {
  RELOAD: { thunk: () => window.location.reload() },
}
```
This also violates global, even though property is allowed

**Comment by getify** [comment]
That's working as intended: those are both "global"-scope arrow functions, which is to say they derive their "lexical `this`" binding from that global scope.

**Comment by Guria** [comment]
Ok, thank you for your feedback
