### ISSUE TITLE
eslint v9 compatibility

### ISSUE THREAD

**Issue by lgenzelis** [getify/eslint-plugin-proper-arrows#37]
The latest version of the plugin (11.0.3) is not compatible with eslint v9. Trying to use it results in the error `TypeError: context.getScope is not a function`. 

According to [the official eslint docs](https://eslint.org/docs/latest/use/troubleshooting/v9-rule-api-changes), this happens because

> ESLint v9.0.0 introduces [changes to the rules API](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) that plugin rules use, which included moving some methods from the context object to the sourceCode object

**Comment by lgenzelis** [comment]
What about creating a new major version that only supports eslint v9? Or is it your intention to continue to make changes to the plugin in the future, and you explicitly want to make those changes available to older eslint versions?

**Comment by getify** [comment]
I am not currently investing effort in this plugin, so fixing breaking changes that eslint decided to make (which I still sorta disagree with, but whatever) is not high on my list. But moreover, having then to need two separate projects (or branches or whatever) that have to be maintained --not just adding of features, but fixing bugs or security issues, etc -- is even more work, and even harder to justify.

I wouldn't block efforts by other contributors to do so, but it's just not something I have planned to prioritize here.

So, IOW... PRs accepted. ;-)

**Comment by Smrtnyk** [comment]
I have opened a PR https://github.com/getify/eslint-plugin-proper-arrows/pulls
in case Kyle is willing to consider it

**Comment by getify** [comment]
thanks @Smrtnyk for all the contributions to land those changes!

**Comment by chelentos** [comment]
Hello!

Could you tell please when will be published eslint 9 version of package?
